ALTER TABLE Reservation ADD COLUMN archived BOOLEAN DEFAULT 0;
ALTER TABLE Reservation ADD COLUMN archivedAt TEXT;
ALTER TABLE Reservation ADD COLUMN archivedReason TEXT;

ALTER TABLE Payment ADD COLUMN archived BOOLEAN DEFAULT 0;
ALTER TABLE Payment ADD COLUMN archivedAt TEXT;
ALTER TABLE Payment ADD COLUMN archivedReason TEXT;

ALTER TABLE Contract ADD COLUMN archived BOOLEAN DEFAULT 0;
ALTER TABLE Contract ADD COLUMN archivedAt TEXT;
ALTER TABLE Contract ADD COLUMN archivedReason TEXT;
